# -*- mode: python ; coding: utf-8 -*-
"""
PyInstaller spec para BMB Encover Agent (.exe para Windows)
Uso: pyinstaller bmb-encover.spec
"""
import sys
import os
from pathlib import Path
import os

ROOT = Path.cwd().resolve()

block_cipher = None

# Todos los paquetes ocultos que necesita BMB
hidden_imports = [
    # Core
    "bmb_cli",
    "bmb_cli.main",
    "bmb_cli.config",
    "bmb_cli.setup",
    "bmb_cli.providers",
    "bmb_cli.model_catalog",
    "bmb_cli.gateway",
    "bmb_cli.auth",
    "bmb_cli.auth_commands",
    "bmb_cli.models",
    "bmb_cli.logs",
    "bmb_cli.cron",
    "bmb_cli.voice",
    "bmb_cli.plugins",
    "bmb_cli.skills_hub",
    "bmb_cli.skill_commands",
    "bmb_cli.skin_engine",
    "bmb_cli.banner",
    "bmb_cli.tips",
    "bmb_cli.env_loader",
    "bmb_cli.profiles",
    "bmb_cli.curator",
    "bmb_cli.doctor",
    "bmb_cli.hooks",
    "bmb_cli.plugins_cmd",
    "bmb_cli.tools_config",
    "bmb_cli.skills_config",
    "bmb_cli.mcp_config",
    "bmb_cli.clipboard",
    "bmb_cli.pty_bridge",
    "bmb_cli.dump",
    "bmb_cli.backup",
    "bmb_cli.web_server",
    "bmb_cli.curses_ui",
    "bmb_cli.uninstall",
    "bmb_cli.debug",
    "bmb_cli.pairing",
    "bmb_cli.kanban",
    "bmb_cli.kanban_db",
    "bmb_cli.runtime_provider",
    "bmb_cli.model_switch",
    "bmb_cli.model_normalize",
    "bmb_cli.oneshot",
    "bmb_cli.goals",
    "bmb_cli.claw",
    "bmb_cli._parser",
    "bmb_cli.slack_cli",
    "bmb_cli.status",
    "bmb_cli.timeouts",
    "bmb_cli.callbacks",
    "bmb_cli.completion",
    "bmb_cli.relaunch",
    "bmb_cli.azure_detect",
    "bmb_cli.default_soul",
    "bmb_cli.copilot_auth",
    "bmb_cli.memory_setup",
    "bmb_cli.platforms",
    "bmb_cli.cli_output",
    "bmb_cli.browser_connect",
    "bmb_cli.nous_subscription",
    "bmb_cli.auth_commands",
    "bmb_cli.ft",
    "bmb_cli.ingest",
    # Agent
    "agent",
    "agent.prompt_builder",
    "agent.memory_manager",
    "agent.memory_provider",
    "agent.skill_utils",
    "agent.skill_commands",
    "agent.skill_preprocessing",
    "agent.display",
    "agent.display_helpers",
    "agent.insights",
    "agent.redact",
    "agent.file_safety",
    "agent.credential_pool",
    "agent.credential_sources",
    "agent.google_oauth",
    "agent.model_metadata",
    "agent.image_gen_provider",
    "agent.image_gen_registry",
    "agent.context_references",
    "agent.context_engine",
    "agent.curator",
    "agent.curator_backup",
    "agent.auxiliary_client",
    "agent.account_usage",
    "agent.bedrock_adapter",
    "agent.anthropic_adapter",
    "agent.gemini_native_adapter",
    "agent.gemini_cloudcode_adapter",
    "agent.copilot_acp_client",
    "agent.shell_hooks",
    "agent.transports.chat_completions",
    "agent.transports.codex_responses",
    "agent.transports.base",
    "agent.onboarding",
    # Tools
    "tools",
    "tools.registry",
    "tools.terminal_tool",
    "tools.file_tools",
    "tools.web_tools",
    "tools.browser_tool",
    "tools.browser_camofox",
    "tools.browser_camofox_state",
    "tools.browser_providers.browser_use",
    "tools.browser_providers.base",
    "tools.browser_cdp_tool",
    "tools.memory_tool",
    "tools.skills_tool",
    "tools.skills_hub",
    "tools.skill_manager_tool",
    "tools.skill_usage",
    "tools.delegate_tool",
    "tools.send_message_tool",
    "tools.code_execution_tool",
    "tools.vision_tools",
    "tools.transcription_tools",
    "tools.tts_tool",
    "tools.image_generation_tool",
    "tools.voice_mode",
    "tools.cronjob_tools",
    "tools.session_search_tool",
    "tools.kanban_tools",
    "tools.approval",
    "tools.url_safety",
    "tools.mcp_tool",
    "tools.mcp_oauth",
    "tools.mcp_oauth_manager",
    "tools.checkpoint_manager",
    "tools.process_registry",
    "tools.credential_files",
    "tools.env_passthrough",
    "tools.tirith_security",
    "tools.osv_check",
    "tools.tool_output_limits",
    "tools.interrupt",
    "tools.skills_sync",
    "tools.skills_guard",
    "tools.file_state",
    "tools.browser_supervisor",
    "tools.rl_training_tool",
    "tools.website_policy",
    "tools.debug_helpers",
    "tools.managed_tool_gateway",
    "tools.xai_http",
    "tools.environments.local",
    "tools.environments.base",
    "tools.environments.file_sync",
    # Gateway
    "gateway",
    "gateway.run",
    "gateway.session",
    "gateway.config",
    "gateway.delivery",
    "gateway.hooks",
    "gateway.status",
    "gateway.platform_registry",
    "gateway.platforms.telegram",
    "gateway.platforms.discord",
    "gateway.platforms.slack",
    "gateway.platforms.whatsapp",
    "gateway.platforms.email",
    "gateway.platforms.webhook",
    "gateway.platforms.base",
    "gateway.platforms.helpers",
    # ACP
    "acp_adapter",
    "acp_adapter.server",
    "acp_adapter.session",
    "acp_adapter.tools",
    "acp_adapter.auth",
    "acp_adapter.permissions",
    # Cron
    "cron",
    "cron.scheduler",
    "cron.jobs",
    # Constantes
    "bmb_constants",
    "bmb_state",
    "bmb_time",
    "bmb_logging",
]

datas = [
    # Skills (para que el agente pueda cargarlos)
    (str(ROOT / "skills"), "skills"),
    # Plugins
    (str(ROOT / "plugins"), "plugins"),
    # Assets del gateway
    (str(ROOT / "gateway" / "assets"), "gateway/assets"),
]

# Excluir lo que no sirve en Windows
excludes = [
    "tkinter",
    "PyQt5",
    "PySide",
    "gi",  # GTK
    "matplotlib",
    "scipy",
    "pandas",
    "notebook",
    "jupyter",
    "test",
    "tests",
]

# Estos módulos son necesarios pero PyInstaller no los detecta automáticamente
# Añadirlos como hiddenimports extra
extra_hidden = [
    "unittest",
    "unittest.mock",
    "unittest.case",
    "unittest.suite",
    "unittest.runner",
    "unittest.result",
    "unittest.util",
    "unittest.loader",
    "unittest.main",
    "unittest.signals",
    "unittest._log",
    "unittest._outcome",
    "unittest._str_issue",
    "_io",
    "socket",
    "selectors",
    "select",
    "email",
    "email.mime",
    "email.mime.text",
    "email.mime.multipart",
    "email.mime.base",
    "email.charset",
    "email.encoders",
    "email.header",
    "http",
    "http.client",
    "urllib",
    "urllib.parse",
    "urllib.request",
    "urllib.error",
    "json.decoder",
    "json.encoder",
    "json.scanner",
    "json.tool",
    "ctypes",
    "ctypes._endian",
    "queue",
    "threading",
    "multiprocessing",
    "multiprocessing.util",
    "multiprocessing.process",
    "multiprocessing.connection",
    "concurrent",
    "concurrent.futures",
    "concurrent.futures.thread",
    "concurrent.futures.process",
    "asyncio",
    "asyncio.base_events",
    "asyncio.base_futures",
    "asyncio.base_subprocess",
    "asyncio.base_tasks",
    "asyncio.constants",
    "asyncio.coroutines",
    "asyncio.events",
    "asyncio.exceptions",
    "asyncio.format_helpers",
    "asyncio.futures",
    "asyncio.locks",
    "asyncio.log",
    "asyncio.protocols",
    "asyncio.proactor_events",
    "asyncio.queues",
    "asyncio.runners",
    "asyncio.selector_events",
    "asyncio.sslproto",
    "asyncio.staggered",
    "asyncio.streams",
    "asyncio.subprocess",
    "asyncio.taskgroups",
    "asyncio.tasks",
    "asyncio.threads",
    "asyncio.timeouts",
    "asyncio.transports",
    "asyncio.trsock",
    "asyncio.unix_events",
    "asyncio.windows_events",
    "asyncio.windows_utils",
    "asyncio.write",
    "xml",
    "xml.parsers",
    "xml.parsers.expat",
    "xml.sax",
    "xml.sax.handler",
    "xml.sax.saxutils",
    "xml.sax.expatreader",
    "xml.dom",
    "xml.dom.minidom",
    "xml.etree",
    "xml.etree.ElementTree",
    "html",
    "html.parser",
    "html.entities",
    "csv",
    "io",
    "pathlib",
    "fnmatch",
    "glob",
    "shutil",
    "tempfile",
    "hashlib",
    "hmac",
    "base64",
    "binascii",
    "struct",
    "textwrap",
    "pprint",
    "copy",
    "weakref",
    "types",
    "enum",
    "dataclasses",
    "abc",
    "collections",
    "collections.abc",
    "itertools",
    "functools",
    "operator",
    "inspect",
    "traceback",
    "linecache",
    "tokenize",
    "ast",
    "compileall",
    "dis",
    "pickle",
    "pickletools",
    "shelve",
    "dbm",
    "sqlite3",
    "sqlite3.dbapi2",
    "sqlite3.dump",
    "zoneinfo",
    "calendar",
    "datetime",
    "email._policybase",
    "email.feedparser",
    "email.message",
    "email.parser",
    "email.errors",
    "email.headerregistry",
    "email.contentmanager",
    "email.policy",
    "email.iterators",
    "email.generator",
    "email.mime.application",
    "email.mime.audio",
    "email.mime.image",
    "email.mime.message",
    "email.mime.nonmultipart",
    "getpass",
    "platform",
    "subprocess",
    "signal",
    "contextvars",
    "importlib",
    "importlib.metadata",
    "importlib.resources",
    "importlib.util",
    "importlib.abc",
    "importlib._bootstrap",
    "importlib._bootstrap_external",
    "pkgutil",
    "pkg_resources",
    "__future__",
]
a = Analysis(
    ["bmb_cli/main.py"],
    pathex=[str(ROOT)],
    binaries=[],
    datas=datas,
    hiddenimports=hidden_imports + extra_hidden,
    hookspath=[],
    hooksconfig={},
    runtime_hooks=[],
    excludes=excludes,
    noarchive=False,
    module_collection_mode={
        "bmb_cli": "py",
        "agent": "pyz",
        "tools": "pyz",
        "gateway": "pyz",
    },
)

pyz = PYZ(a.pure, a.zipped_data, cipher=block_cipher)

exe = EXE(
    pyz,
    a.scripts,
    a.binaries,
    a.zipfiles,
    a.datas,
    [],
    name="bmb",
    debug=False,
    bootloader_ignore_signals=False,
    strip=False,
    upx=True,
    upx_exclude=[],
    runtime_tmpdir=None,
    console=True,  # CLI tool, necesita consola
    disable_windowed_traceback=False,
    argv_emulation=False,
    target_arch=None,
    codesign_identity=None,
    entitlements_file=None,
    icon=str(ROOT / "assets" / "bmb.ico") if (ROOT / "assets" / "bmb.ico").exists() else None,
)
